(tag_name) @tag
(erroneous_end_tag_name) @tag.error
(doctype) @constant
(attribute_name) @attribute
(attribute_value) @string
(comment) @comment

[
  "<"
  ">"
  "</"
  "/>"
] @punctuation.bracket

; DO NOT EDIT - This file is generated by `cargo xtask gen-crates`
; To modify, edit the source in grammars/tree-sitter-*/queries/
; or add extra_injections in grammars/tree-sitter-*/grammar-crate-config.toml

[
  (dynamic_directive_inner_value)
] @tag

[
  "["
  "]"
] @punctuation.bracket

(interpolation) @punctuation.special

(interpolation
  (raw_text) @none)

(directive_name) @tag.attribute

(directive_attribute
  (quoted_attribute_value) @punctuation.special)

(directive_attribute
  (quoted_attribute_value
    (attribute_value) @none))

[
  (directive_modifier)
  (directive_value)
] @function.method
